<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryLatest()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM AppBundle:Message p
                WHERE p.createtime <= :now
                ORDER BY p.createtime DESC
            ')
            ->setParameter('now', new \DateTime())
            ;
    }

    public function findLatest()
    {
        $this->queryLatest()->getResult();
    }
}
