# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        database_users:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            provider: database_users
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login_check

            logout:
                path: user_logout
                target: homepage